// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type Role string

const (
	RoleMember     Role = "member"
	RoleOwner      Role = "owner"
	RoleAdmin      Role = "admin"
	RoleInstructor Role = "instructor"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Class struct {
	ID           int32
	GymID        sql.NullInt32
	AttendeeID   sql.NullInt32
	InstructorID sql.NullInt32
	Date         time.Time
	MaxAttendees int32
	ClassType    sql.NullString
}

type Gym struct {
	ID       int32
	Name     string
	OwnerID  sql.NullInt32
	MemberID sql.NullInt32
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt sql.NullTime
	Role      NullRole
}
