// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, password, created_at, role)
VALUES 
  ($1, $2, NOW(), $3)
`

type CreateUserParams struct {
	Email    string
	Password string
	Role     NullRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.Password, arg.Role)
	return err
}
